[build]
builder = "nixpacks"
buildCommand = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"

[deploy]
startCommand = "node server/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
